name: Deploy to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login https://docker.pkg.github.com -u auguwu --password-stdin
      - name: Build
        run: docker build -t docker.pkg.github.com/ninodiscord/timeouts/timeouts:latest .
      - name: Push
        run: docker push docker.pkg.github.com/ninodiscord/timeouts/timeouts:latest
